# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Astat < Formula
  desc "A Lightning fast local AWS Stats indexer"
  homepage "https://github.com/sunil-saini/astat"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sunil-saini/astat/releases/download/v0.1.8/astat_0.1.8_darwin_x86_64.tar.gz"
      sha256 "e62b3d18928b8e8384712eff6ed9d1b9164cb1a448a3ba2c1f424e5cee7e4549"

      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sunil-saini/astat/releases/download/v0.1.8/astat_0.1.8_darwin_arm64.tar.gz"
      sha256 "fac7512e82de932cc78312c9872c154285afc33be75523d3dee286776a0f0fb1"

      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunil-saini/astat/releases/download/v0.1.8/astat_0.1.8_linux_x86_64.tar.gz"
      sha256 "9d7742592a7e193736062f658441e96867adbf450dd55c36293514a8fbbcd220"
      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunil-saini/astat/releases/download/v0.1.8/astat_0.1.8_linux_arm64.tar.gz"
      sha256 "270d2c7f8e18be0b53607010899388e2c7d7ff6e39d12012a947fc3df430aaa7"
      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
  end

  def post_install
    system "#{bin}/astat", "install"
  end

  test do
    system "#{bin}/astat", "version"
  end
end
