# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Astat < Formula
  desc "A Lightning fast local AWS Stats indexer"
  homepage "https://github.com/sunil-saini/astat"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sunil-saini/astat/releases/download/v0.0.1/astat_0.0.1_darwin_x86_64.tar.gz"
      sha256 "a5fbe726ef3deed0b51635ff4730600ad13a06ab5a6f510202b2f9dcafe43e71"

      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sunil-saini/astat/releases/download/v0.0.1/astat_0.0.1_darwin_arm64.tar.gz"
      sha256 "8418dc67a2a255674bff5d0629add06d2ac50d66c4a96159fc3ac9e17bcf1e55"

      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunil-saini/astat/releases/download/v0.0.1/astat_0.0.1_linux_x86_64.tar.gz"
      sha256 "9f231c0e24a89f3034864562cde7f1679da14c8efd101b13cd86c4f7fee40314"
      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunil-saini/astat/releases/download/v0.0.1/astat_0.0.1_linux_arm64.tar.gz"
      sha256 "b0eb072b21c630ca65e974562d2cfc949c8f49a976babd9e02936e0843dec0d0"
      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
  end

  test do
    system "#{bin}/astat", "version"
  end
end
