# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Astat < Formula
  desc "A blazing fast CLI tool that caches AWS resources details locally and provides deep infrastructure tracing"
  homepage "https://github.com/sunil-saini/astat"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sunil-saini/astat/releases/download/v0.1.8/astat_0.1.8_darwin_x86_64.tar.gz"
      sha256 "4a8cbc6e833559150126c9c5d4ad11156f25b0c357f9ba1da48174be0a0a4587"

      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sunil-saini/astat/releases/download/v0.1.8/astat_0.1.8_darwin_arm64.tar.gz"
      sha256 "dd3f39c69c4a83a47aeb41c3e1b8667e83a24c1781f2bb71ba17ec04dcb35e88"

      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunil-saini/astat/releases/download/v0.1.8/astat_0.1.8_linux_x86_64.tar.gz"
      sha256 "30f0a00dc97c53821e197e0994161dc08b4c30289d4688f8271e5ebc4874bf36"
      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunil-saini/astat/releases/download/v0.1.8/astat_0.1.8_linux_arm64.tar.gz"
      sha256 "4020506daf90eb84cd3cf351b4eba2848c30099c3de531daa7533d08ca19a255"
      def install
        bin.install "astat"
        bash_completion.install "completions/astat.bash" => "astat"
        zsh_completion.install "completions/astat.zsh" => "_astat"
        fish_completion.install "completions/astat.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To initialize configuration and cache, run:
        astat install
    EOS
  end

  test do
    system "#{bin}/astat", "version"
  end
end
